spring:
  application:
    name: skillbridge-api

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbridge
    username: postgres
    password: admin5652

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
